### ISSUE TITLE
Integrate app files

### ISSUE THREAD

**Issue by mgdesign** [sparkfabrik/docker-locke-server#1]
Integrate the following app files that will be copied and used in the container:
- server.js
- theme folder
- assest folder
- content folder

**Comment by stickgrinder** [comment]
Is this issue stull open?

I guess this refers to a previous implementation, where Locke was not split in server and distribution. Am I right? Can this be closed?

**Comment by mgdesign** [comment]
Yes, I think this can be considered outdated anyway.
